name: Keep Render App Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # A cada 10 minutos
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -s https://analisador-de-curr-culos.onrender.com || echo "App está dormindo ou offline"
